# Generated by Django 6.0.6 on 2026-08-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_tag_rename_field_name_author_name_author_bio_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='books', to='tracker.tag'),
        ),
    ]
